### ISSUE TITLE
Plugin Tool settings do not persist

### ISSUE THREAD

**Issue by knatz-dev** [lesma/FanFiction-Tools#1]
The tool settings revert to default after some time. 
I did not clear cookies during this time or close the browser.

**Comment by lesma** [comment]
@knatz-personal That is rather odd, its always worked for me!

It actually uses local storage rather than cookies for storing data, and should only be cleared if you were to clear all cookies for the entire time range.

To help try and track down this error can I ask the following questions:
1. Has this ever worked for you, if it has is their any pattern to it failing/steps to reproduce
2. If you are familiar with Firebug developer tools can you look at the storage inspectors local storage and see if data is being written their at all and see if anything is written to the error console
3. Please confirm that you have plenty of disc space and are not running in "private mode"
4. Can you let me know what OS/Browser version you are using

**Comment by knatz-dev** [comment]
<a href="http://www.sherv.net/"><img alt="Embarrassed smiley face" width=47 height=49 src="http://www.sherv.net/cm/emoticons/embarrassed/embarrassed-smiley-face.gif"></a> I don't know of if you did something but its been several hours since i saved my settings and they have not disappeared. I think it has mysteriously resolved itself so thanks for the help and sorry for the inconvenience.

As for the plugin itself I like it a lot and think its a great idea to get around ffnet's filtering limitations.
