### ISSUE TITLE
Improve filtering

### ISSUE THREAD

**Issue by lesma** [lesma/FanFiction-Tools#8]
- Allow filtering on multiple characters positively and negatively

**Comment by i30817** [comment]
Please make the god-awful 'community groups' ([for example](https://www.fanfiction.net/community/The-Video-Game-Plot/105176/)) of stories actually allow filtering positively and negatively. The blacklist setting helps to filter negatively but this is a punctual thing not often something you want to keep on a setting, and there is no possibility of character or genre filtering in story thematic groups (probably because they belong to unrestricted fandoms).

Therefore, i'd like a searchbox on every group page (side by side with the positive filters already there) without the (impossible, infinite) dropdown box. If it works on character names and genre, great, if not, the text of synopsis will do.

I think a api that uses - and + for searching on a single searchbox on groups would be enough (like lucene can for example).

**Comment by lesma** [comment]
Sorry for the delay, still just scraped in under a year!

Unfortunately am limited in what I can do due to not having access to fanfiction.net, this extension can only modify the page. That said, have just ported the fanfic-filter into a Firefox web extension add on, which is now available at: https://addons.mozilla.org/en-GB/firefox/addon/fanfic-filter-quantum/ git hub for this is in https://github.com/lesma/FanFic-Filter.

This does allow some filtering of communities via the summary filters box. Unfortunately there is no simple way to get a list of characters on the page. As this is not present on the page already.

In the latest version of Fanfiction-tools (released yesterday) I added an option to indicate you are also using fanfic filter which disables conflicting functionality in fanfiction tools.
